#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const sourcePath = path.join(root, "data/source/playable-avatars.json");
const outputPath = path.join(root, "internal/game/npc_avatars_generated.go");
const source = JSON.parse(fs.readFileSync(sourcePath, "utf8"));

if (
  source.schema !== "new-yokosuka-shenmue1-playable-avatars-v1"
  || !Array.isArray(source.avatars)
  || source.avatars.length === 0
) {
  throw new Error("The playable-avatar source manifest is invalid");
}

const ids = source.avatars.map(({ id }) => id);
if (
  ids.some((id) => typeof id !== "string" || !/^s1-[a-z0-9-]+$/.test(id))
  || new Set(ids).size !== ids.length
) {
  throw new Error("Playable-avatar IDs must be unique normalized strings");
}

const entries = ids.map((id) => `\t${JSON.stringify(id)}: {},`).join("\n");
const output = `// Code generated by tools/generate/build_playable_avatar_allowlist.mjs; DO NOT EDIT.

package game

var validNPCAvatars = map[string]struct{}{
${entries}
}
`;

fs.writeFileSync(outputPath, output);
process.stdout.write(`Wrote ${ids.length} Shenmue I NPC avatar IDs.\n`);
